[package]
name = "c-encode"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
encoding_rs = "0.8.33"
libc = "0.2.153"
widestring = "1.1.0"
winapi = { version = "0.3.9", features = ["winuser"] }
